### ISSUE TITLE
not compatible Qgis 3/python 3

### ISSUE THREAD

**Issue by mmetois** [geolovic/SwathProfiler#3]
Hi, 
I would be interested in using your swath profiler tool, though it appears incompatible with Qgis 3 and Python 3.8. 
Do you plan to make a compatible version with python 3.8 ? 
Many thanks, 
Marianne

**Comment by pbessin** [comment]
Dear collegue,

I would like to use your great toolbox on QGIS 3 but it returns the following error when i try to add the scrip from file :
NameError: name 'Line_shapefile' is not defined 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\script\ScriptAlgorithmProvider.py", line 121, in loadAlgorithms
    alg = ScriptUtils.loadAlgorithm(moduleName, filePath)
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\script\ScriptUtils.py", line 66, in loadAlgorithm
    spec.loader.exec_module(module)
  File "", line 728, in exec_module
  File "", line 219, in _call_with_frames_removed
  File "C:\Users\Paul_BESSIN\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\SwathProfile.py", line 52, in 
    line_shp = str(Line_shapefile)
NameError: name 'Line_shapefile' is not defined

I'm pretty sure that this is not a great trouble but I m not enough good at Python programming to debug it.

Do you see how to solve that error in a simple way?

Thank you for providing this free toolbox on a free software.

Best regards,

Paul
